CREATE TABLE AIRLINE (
    AirlineID VARCHAR2(20) PRIMARY KEY,
    AirlineName VARCHAR2(100) NOT NULL,
    Country VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE
);

CREATE TABLE AIRPORT (
    AirportID VARCHAR2(20) PRIMARY KEY,
    AirportName VARCHAR2(150) NOT NULL,
    City VARCHAR2(100) NOT NULL,
    Country VARCHAR2(100) NOT NULL,
    IATACode CHAR(3) UNIQUE
);

CREATE TABLE AIRCRAFT (
    AircraftID VARCHAR2(20) PRIMARY KEY,
    AirlineID VARCHAR2(20),
    Model VARCHAR2(100) NOT NULL,
    Capacity NUMBER CHECK (Capacity > 0),
    ManufactureYear NUMBER,
    CONSTRAINT fk_aircraft_airline FOREIGN KEY (AirlineID) REFERENCES AIRLINE(AirlineID)
);

CREATE TABLE ROUTE (
    RouteID VARCHAR2(20) PRIMARY KEY,
    DepartureAirportID VARCHAR2(20),
    ArrivalAirportID VARCHAR2(20),
    Distance NUMBER,
    EstimatedTime NUMBER,
    CONSTRAINT fk_route_dep FOREIGN KEY (DepartureAirportID) REFERENCES AIRPORT(AirportID),
    CONSTRAINT fk_route_arr FOREIGN KEY (ArrivalAirportID) REFERENCES AIRPORT(AirportID),
    CONSTRAINT chk_route_diff CHECK (DepartureAirportID <> ArrivalAirportID)
);

CREATE TABLE FLIGHT (
    FlightID VARCHAR2(20) PRIMARY KEY,
    FlightNumber VARCHAR2(50) UNIQUE,
    AirlineID VARCHAR2(20),
    AircraftID VARCHAR2(20),
    RouteID VARCHAR2(20),
    DepartureTime DATE NOT NULL,
    ArrivalTime DATE,
    Gate VARCHAR2(10),
    FlightStatus VARCHAR2(50) DEFAULT 'SCHEDULED',
    CONSTRAINT fk_flight_airline FOREIGN KEY (AirlineID) REFERENCES AIRLINE(AirlineID),
    CONSTRAINT fk_flight_aircraft FOREIGN KEY (AircraftID) REFERENCES AIRCRAFT(AircraftID),
    CONSTRAINT fk_flight_route FOREIGN KEY (RouteID) REFERENCES ROUTE(RouteID),
    CONSTRAINT chk_flight_time CHECK (ArrivalTime > DepartureTime),
    CONSTRAINT chk_flight_status CHECK (FlightStatus IN ('SCHEDULED', 'DELAYED', 'CANCELLED', 'LANDED', 'COMPLETED'))
);

CREATE TABLE USERS (
    UserID VARCHAR2(20) PRIMARY KEY,
    FullName VARCHAR2(150) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1))
);

CREATE TABLE ACCOUNT (
    AccountID VARCHAR2(20) PRIMARY KEY,
    UserID VARCHAR2(20),
    UserName VARCHAR2(100) UNIQUE NOT NULL,
    Password VARCHAR2(200) NOT NULL,
    Status VARCHAR2(50) DEFAULT 'ACTIVE',
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1)),
    CONSTRAINT fk_account_user FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    CONSTRAINT chk_account_status CHECK (Status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'LOCKED'))
);

CREATE TABLE CUSTOMER (
    CustomerID VARCHAR2(20) PRIMARY KEY,
    AccountID VARCHAR2(20) UNIQUE,
    FullName VARCHAR2(150) NOT NULL,
    Gender VARCHAR2(10),
    DateOfBirth DATE,
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    PassportNumber VARCHAR2(50) UNIQUE,
    Nationality VARCHAR2(50),
    CONSTRAINT fk_customer_account FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID),
    CONSTRAINT chk_customer_gender CHECK (Gender IN ('Male', 'Female', 'Other'))
);

CREATE TABLE EMPLOYEE (
    EmployeeID VARCHAR2(20) PRIMARY KEY,
    AccountID VARCHAR2(20) UNIQUE,
    FullName VARCHAR2(150) NOT NULL,
    Position VARCHAR2(100),
    Phone VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE,
    CONSTRAINT fk_employee_account FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
);

CREATE TABLE SEAT (
    SeatID VARCHAR2(20) PRIMARY KEY,
    AircraftID VARCHAR2(20),
    SeatNumber VARCHAR2(10) NOT NULL,
    Class VARCHAR2(20),
    CONSTRAINT fk_seat_aircraft FOREIGN KEY (AircraftID) REFERENCES AIRCRAFT(AircraftID),
    CONSTRAINT uq_seat UNIQUE (AircraftID, SeatNumber),
    CONSTRAINT chk_seat_class CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First Class'))
);

CREATE TABLE BOOKING (
    BookingID VARCHAR2(20) PRIMARY KEY,
    CustomerID VARCHAR2(20),
    EmployeeID VARCHAR2(20),
    BookingDate DATE DEFAULT SYSDATE NOT NULL,
    TotalAmount NUMBER DEFAULT 0 CHECK (TotalAmount >= 0),
    Status VARCHAR2(50) DEFAULT 'PENDING',
    CONSTRAINT fk_booking_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    CONSTRAINT fk_booking_employee FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
    CONSTRAINT chk_booking_status CHECK (Status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'))
);

CREATE TABLE PASSENGER (
    PassengerID VARCHAR2(20) PRIMARY KEY,
    FullName VARCHAR2(150) NOT NULL,
    Gender VARCHAR2(10),
    DateOfBirth DATE,
    PassportNumber VARCHAR2(50) UNIQUE,
    CONSTRAINT chk_passenger_gender CHECK (Gender IN ('Male','Female','Other'))
);

CREATE TABLE TICKET (
    TicketID VARCHAR2(20) PRIMARY KEY,
    BookingID VARCHAR2(20),
    FlightID VARCHAR2(20),
    SeatID VARCHAR2(20),
    PassengerID VARCHAR2(20),
    Price NUMBER CHECK (Price > 0),
    TicketStatus VARCHAR2(50) DEFAULT 'BOOKED',
    CONSTRAINT fk_ticket_booking FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
    CONSTRAINT fk_ticket_flight FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID),
    CONSTRAINT fk_ticket_seat FOREIGN KEY (SeatID) REFERENCES SEAT(SeatID),
    CONSTRAINT fk_ticket_passenger FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID),
    CONSTRAINT uq_passenger_flight UNIQUE (PassengerID, FlightID),
    CONSTRAINT chk_ticket_status CHECK (TicketStatus IN ('BOOKED','PAID','CANCELLED','CHECKED-IN'))
);

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX UQ_TICKET_SEAT_ACTIVE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
--dùng để đảm bảo không có 2 vé cùng ghế trên 1 chuyến bay
CREATE UNIQUE INDEX UQ_TICKET_SEAT_ACTIVE ON TICKET (
    CASE WHEN TicketStatus != 'CANCELLED' THEN FlightID ELSE NULL END,
    CASE WHEN TicketStatus != 'CANCELLED' THEN SeatID ELSE NULL END
);

CREATE TABLE PAYMENT (
    PaymentID VARCHAR2(20) PRIMARY KEY,
    BookingID VARCHAR2(20),
    PaymentDate DATE DEFAULT SYSDATE NOT NULL,
    Amount NUMBER CHECK (Amount > 0),
    PaymentMethod VARCHAR2(50),
    PaymentStatus VARCHAR2(50),
    CONSTRAINT fk_payment_booking FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
    CONSTRAINT chk_payment_method CHECK (PaymentMethod IN ('CREDIT CARD', 'BANK TRANSFER','MOMO')),
    CONSTRAINT chk_payment_status CHECK (PaymentStatus IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE BAGGAGE (
    BaggageID VARCHAR2(20) PRIMARY KEY,
    TicketID VARCHAR2(20),
    Weight NUMBER CHECK (Weight >= 0),
    BaggageType VARCHAR2(50),
    CONSTRAINT fk_baggage_ticket FOREIGN KEY (TicketID) REFERENCES TICKET(TicketID),
    CONSTRAINT chk_baggage_type CHECK (BaggageType IN ('Carry-on', 'Checked','Fragile', 'Oversized'))
);

CREATE TABLE TRANSACTION_HISTORY (
    TransactionID VARCHAR2(20) PRIMARY KEY,
    CustomerID VARCHAR2(20),
    BookingID VARCHAR2(20),
    PaymentID VARCHAR2(20),
    TransactionType VARCHAR2(50),
    Amount NUMBER CHECK (Amount >= 0),
    TransactionDate DATE DEFAULT SYSDATE NOT NULL,
    Description VARCHAR2(255),
    CONSTRAINT fk_th_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
    CONSTRAINT fk_th_booking FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
    CONSTRAINT fk_th_payment FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID)
);

CREATE TABLE SEATCLASSPRICE (
    PriceID VARCHAR2(20) PRIMARY KEY,
    FlightID VARCHAR2(20),
    Class VARCHAR2(20),
    Price NUMBER CHECK (Price >= 0),
    CONSTRAINT fk_price_flight FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID),
    CONSTRAINT chk_price_class CHECK (Class IN ('Economy', 'Premium Economy', 'Business', 'First Class'))
);

CREATE TABLE "FUNCTION" (
    FunctionID VARCHAR2(20) PRIMARY KEY,
    NameFunction VARCHAR2(100) NOT NULL,
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1))
);

CREATE TABLE ROLE (
    RoleID VARCHAR2(20) PRIMARY KEY,
    FunctionID VARCHAR2(20),
    AddPerm NUMBER CHECK (AddPerm IN (0,1)),
    EditPerm NUMBER CHECK (EditPerm IN (0,1)),
    DeletePerm NUMBER CHECK (DeletePerm IN (0,1)),
    DownloadPerm NUMBER CHECK (DownloadPerm IN (0,1)),
    ViewPerm NUMBER CHECK (ViewPerm IN (0,1)),
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1)),
    CONSTRAINT fk_role_function FOREIGN KEY (FunctionID) REFERENCES "FUNCTION"(FunctionID)
);

CREATE TABLE ROLE_GROUP (
    RoleGroupID VARCHAR2(20) PRIMARY KEY,
    NameRoleGroup VARCHAR2(100) NOT NULL,
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1))
);

CREATE TABLE ROLE_GROUP_ASSIGN_ROLE (
    RoleGroupID VARCHAR2(20),
    RoleID VARCHAR2(20),
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1)),
    PRIMARY KEY (RoleGroupID, RoleID),
    FOREIGN KEY (RoleGroupID) REFERENCES ROLE_GROUP(RoleGroupID),
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

CREATE TABLE ACCOUNT_ASSIGN_ROLE_GROUP (
    AccountID VARCHAR2(20),
    RoleGroupID VARCHAR2(20),
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1)),
    PRIMARY KEY (AccountID, RoleGroupID),
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID),
    FOREIGN KEY (RoleGroupID) REFERENCES ROLE_GROUP(RoleGroupID)
);

CREATE TABLE ACCOUNT_ASSIGN_ROLE (
    AccountID VARCHAR2(20),
    RoleID VARCHAR2(20),
    Created_At DATE DEFAULT SYSDATE,
    Updated_At DATE DEFAULT SYSDATE,
    IsDeleted NUMBER CHECK (IsDeleted IN (0,1)),
    PRIMARY KEY (AccountID, RoleID),
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID),
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);


-- 1. XÓA CÁC BẢNG PHÂN QUYỀN (Auth & Roles)
DROP TABLE ACCOUNT_ASSIGN_ROLE CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_ASSIGN_ROLE_GROUP CASCADE CONSTRAINTS;
DROP TABLE ROLE_GROUP_ASSIGN_ROLE CASCADE CONSTRAINTS;
DROP TABLE ROLE_GROUP CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
DROP TABLE "FUNCTION" CASCADE CONSTRAINTS;

-- 2. XÓA CÁC BẢNG GIAO DỊCH, THANH TOÁN & VÉ
DROP TABLE TRANSACTION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE BAGGAGE CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;

-- 3. XÓA CÁC BẢNG THỰC THỂ CON NGƯỜI (Users, Customers, Employees...)
DROP TABLE PASSENGER CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 4. XÓA CÁC BẢNG DANH MỤC BAY & MÁY BAY
DROP TABLE SEATCLASSPRICE CASCADE CONSTRAINTS;
DROP TABLE FLIGHT CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;
DROP TABLE ROUTE CASCADE CONSTRAINTS;
DROP TABLE AIRCRAFT CASCADE CONSTRAINTS;
DROP TABLE AIRPORT CASCADE CONSTRAINTS;
DROP TABLE AIRLINE CASCADE CONSTRAINTS;
