-- 1. AIRLINE
CREATE SEQUENCE SEQ_AIRLINE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_AIRLINE
BEFORE INSERT ON AIRLINE FOR EACH ROW
BEGIN
    IF :NEW.AirlineID IS NULL THEN
        :NEW.AirlineID := SEQ_AIRLINE.NEXTVAL;
    END IF;
END;


-- 2. AIRPORT
CREATE SEQUENCE SEQ_AIRPORT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_AIRPORT
BEFORE INSERT ON AIRPORT FOR EACH ROW
BEGIN
    IF :NEW.AirportID IS NULL THEN
        :NEW.AirportID := SEQ_AIRPORT.NEXTVAL;
    END IF;
END;


-- 3. AIRCRAFT
CREATE SEQUENCE SEQ_AIRCRAFT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_AIRCRAFT
BEFORE INSERT ON AIRCRAFT FOR EACH ROW
BEGIN
    IF :NEW.AircraftID IS NULL THEN
        :NEW.AircraftID := SEQ_AIRCRAFT.NEXTVAL;
    END IF;
END;


-- 4. ROUTE
CREATE SEQUENCE SEQ_ROUTE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_ROUTE
BEFORE INSERT ON ROUTE FOR EACH ROW
BEGIN
    IF :NEW.RouteID IS NULL THEN
        :NEW.RouteID := SEQ_ROUTE.NEXTVAL;
    END IF;
END;


-- 5. FLIGHT
CREATE SEQUENCE SEQ_FLIGHT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_FLIGHT
BEFORE INSERT ON FLIGHT FOR EACH ROW
BEGIN
    IF :NEW.FlightID IS NULL THEN
        :NEW.FlightID := SEQ_FLIGHT.NEXTVAL;
    END IF;
END;


-- 6. USERS
CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_USERS
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN
    IF :NEW.UserID IS NULL THEN
        :NEW.UserID := SEQ_USERS.NEXTVAL;
    END IF;
END;


-- 7. ACCOUNT
CREATE SEQUENCE SEQ_ACCOUNT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_ACCOUNT
BEFORE INSERT ON ACCOUNT FOR EACH ROW
BEGIN
    IF :NEW.AccountID IS NULL THEN
        :NEW.AccountID := SEQ_ACCOUNT.NEXTVAL;
    END IF;
END;


-- 8. CUSTOMER
CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_CUSTOMER
BEFORE INSERT ON CUSTOMER FOR EACH ROW
BEGIN
    IF :NEW.CustomerID IS NULL THEN
        :NEW.CustomerID := SEQ_CUSTOMER.NEXTVAL;
    END IF;
END;


-- 9. EMPLOYEE
CREATE SEQUENCE SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_EMPLOYEE
BEFORE INSERT ON EMPLOYEE FOR EACH ROW
BEGIN
    IF :NEW.EmployeeID IS NULL THEN
        :NEW.EmployeeID := SEQ_EMPLOYEE.NEXTVAL;
    END IF;
END;


-- 10. SEAT
CREATE SEQUENCE SEQ_SEAT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_SEAT
BEFORE INSERT ON SEAT FOR EACH ROW
BEGIN
    IF :NEW.SeatID IS NULL THEN
        :NEW.SeatID := SEQ_SEAT.NEXTVAL;
    END IF;
END;


-- 11. BOOKING
CREATE SEQUENCE SEQ_BOOKING START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_BOOKING
BEFORE INSERT ON BOOKING FOR EACH ROW
BEGIN
    IF :NEW.BookingID IS NULL THEN
        :NEW.BookingID := SEQ_BOOKING.NEXTVAL;
    END IF;
END;


-- 12. TICKET
CREATE SEQUENCE SEQ_TICKET START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_TICKET
BEFORE INSERT ON TICKET FOR EACH ROW
BEGIN
    IF :NEW.TicketID IS NULL THEN
        :NEW.TicketID := SEQ_TICKET.NEXTVAL;
    END IF;
END;


-- 13. PAYMENT
CREATE SEQUENCE SEQ_PAYMENT START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_PAYMENT
BEFORE INSERT ON PAYMENT FOR EACH ROW
BEGIN
    IF :NEW.PaymentID IS NULL THEN
        :NEW.PaymentID := SEQ_PAYMENT.NEXTVAL;
    END IF;
END;


-- 14. BAGGAGE
CREATE SEQUENCE SEQ_BAGGAGE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_BAGGAGE
BEFORE INSERT ON BAGGAGE FOR EACH ROW
BEGIN
    IF :NEW.BaggageID IS NULL THEN
        :NEW.BaggageID := SEQ_BAGGAGE.NEXTVAL;
    END IF;
END;


-- 15. TRANSACTION_HISTORY
CREATE SEQUENCE SEQ_TRANSACTION_HISTORY START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_TRANSACTION_HISTORY
BEFORE INSERT ON TRANSACTION_HISTORY FOR EACH ROW
BEGIN
    IF :NEW.TransactionID IS NULL THEN
        :NEW.TransactionID := SEQ_TRANSACTION_HISTORY.NEXTVAL;
    END IF;
END;


-- 16. SEATCLASSPRICE
CREATE SEQUENCE SEQ_SEATCLASSPRICE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_SEATCLASSPRICE
BEFORE INSERT ON SEATCLASSPRICE FOR EACH ROW
BEGIN
    IF :NEW.PriceID IS NULL THEN
        :NEW.PriceID := SEQ_SEATCLASSPRICE.NEXTVAL;
    END IF;
END;


-- 17. FUNCTION
CREATE SEQUENCE SEQ_FUNCTION START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_FUNCTION
BEFORE INSERT ON FUNCTION FOR EACH ROW
BEGIN
    IF :NEW.FunctionID IS NULL THEN
        :NEW.FunctionID := SEQ_FUNCTION.NEXTVAL;
    END IF;
END;


-- 18. ROLE
CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_ROLE
BEFORE INSERT ON ROLE FOR EACH ROW
BEGIN
    IF :NEW.RoleID IS NULL THEN
        :NEW.RoleID := SEQ_ROLE.NEXTVAL;
    END IF;
END;


-- 19. ROLE_GROUP
CREATE SEQUENCE SEQ_ROLE_GROUP START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_PK_ROLE_GROUP
BEFORE INSERT ON ROLE_GROUP FOR EACH ROW
BEGIN
    IF :NEW.RoleGroupID IS NULL THEN
        :NEW.RoleGroupID := SEQ_ROLE_GROUP.NEXTVAL;
    END IF;
END;
