BEGIN
  FOR i IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_%') LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || i.sequence_name;
  END LOOP;
END;
/

CREATE SEQUENCE SEQ_AIRLINE START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AIRPORT START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AIRCRAFT START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROUTE START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FLIGHT START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USERS START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNT START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMER START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEAT START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOKING START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TICKET START WITH 15 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BAGGAGE START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSACTION_HISTORY START WITH 8 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEATCLASSPRICE START WITH 11 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCTION START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE START WITH 7 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE_GROUP START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PASSENGER START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE OR REPLACE TRIGGER TRG_AIRLINE_ID 
BEFORE INSERT ON AIRLINE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.AirlineID IS NULL THEN 
    v_seq := SEQ_AIRLINE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.AirlineID := 'AL0' || v_seq; ELSE :NEW.AirlineID := 'AL' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_AIRPORT_ID 
BEFORE INSERT ON AIRPORT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.AirportID IS NULL THEN 
    v_seq := SEQ_AIRPORT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.AirportID := 'AP0' || v_seq; ELSE :NEW.AirportID := 'AP' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_AIRCRAFT_ID 
BEFORE INSERT ON AIRCRAFT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.AircraftID IS NULL THEN 
    v_seq := SEQ_AIRCRAFT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.AircraftID := 'AC0' || v_seq; ELSE :NEW.AircraftID := 'AC' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_ROUTE_ID 
BEFORE INSERT ON ROUTE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.RouteID IS NULL THEN 
    v_seq := SEQ_ROUTE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.RouteID := 'RT0' || v_seq; ELSE :NEW.RouteID := 'RT' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_FLIGHT_ID 
BEFORE INSERT ON FLIGHT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.FlightID IS NULL THEN 
    v_seq := SEQ_FLIGHT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.FlightID := 'FL0' || v_seq; ELSE :NEW.FlightID := 'FL' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_USERS_ID 
BEFORE INSERT ON USERS FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.UserID IS NULL THEN 
    v_seq := SEQ_USERS.NEXTVAL;
    IF v_seq < 10 THEN :NEW.UserID := 'US0' || v_seq; ELSE :NEW.UserID := 'US' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_ID 
BEFORE INSERT ON ACCOUNT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.AccountID IS NULL THEN 
    v_seq := SEQ_ACCOUNT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.AccountID := 'ACC0' || v_seq; ELSE :NEW.AccountID := 'ACC' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_CUSTOMER_ID 
BEFORE INSERT ON CUSTOMER FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.CustomerID IS NULL THEN 
    v_seq := SEQ_CUSTOMER.NEXTVAL;
    IF v_seq < 10 THEN :NEW.CustomerID := 'CUS0' || v_seq; ELSE :NEW.CustomerID := 'CUS' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_ID 
BEFORE INSERT ON EMPLOYEE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.EmployeeID IS NULL THEN 
    v_seq := SEQ_EMPLOYEE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.EmployeeID := 'EMP0' || v_seq; ELSE :NEW.EmployeeID := 'EMP' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_ID 
BEFORE INSERT ON SEAT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.SeatID IS NULL THEN 
    v_seq := SEQ_SEAT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.SeatID := 'ST0' || v_seq; ELSE :NEW.SeatID := 'ST' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_BOOKING_ID 
BEFORE INSERT ON BOOKING FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.BookingID IS NULL THEN 
    v_seq := SEQ_BOOKING.NEXTVAL;
    IF v_seq < 10 THEN :NEW.BookingID := 'BK0' || v_seq; ELSE :NEW.BookingID := 'BK' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_TICKET_ID 
BEFORE INSERT ON TICKET FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.TicketID IS NULL THEN 
    v_seq := SEQ_TICKET.NEXTVAL;
    IF v_seq < 10 THEN :NEW.TicketID := 'TK0' || v_seq; ELSE :NEW.TicketID := 'TK' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_ID 
BEFORE INSERT ON PAYMENT FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.PaymentID IS NULL THEN 
    v_seq := SEQ_PAYMENT.NEXTVAL;
    IF v_seq < 10 THEN :NEW.PaymentID := 'PM0' || v_seq; ELSE :NEW.PaymentID := 'PM' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_BAGGAGE_ID 
BEFORE INSERT ON BAGGAGE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.BaggageID IS NULL THEN 
    v_seq := SEQ_BAGGAGE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.BaggageID := 'BG0' || v_seq; ELSE :NEW.BaggageID := 'BG' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_TRANSACTION_HISTORY_ID 
BEFORE INSERT ON TRANSACTION_HISTORY FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.TransactionID IS NULL THEN 
    v_seq := SEQ_TRANSACTION_HISTORY.NEXTVAL;
    IF v_seq < 10 THEN :NEW.TransactionID := 'TH0' || v_seq; ELSE :NEW.TransactionID := 'TH' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_SEATCLASSPRICE_ID 
BEFORE INSERT ON SEATCLASSPRICE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.PriceID IS NULL THEN 
    v_seq := SEQ_SEATCLASSPRICE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.PriceID := 'SCP0' || v_seq; ELSE :NEW.PriceID := 'SCP' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_FUNCTION_ID 
BEFORE INSERT ON "FUNCTION" FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.FunctionID IS NULL THEN 
    v_seq := SEQ_FUNCTION.NEXTVAL;
    IF v_seq < 10 THEN :NEW.FunctionID := 'FN0' || v_seq; ELSE :NEW.FunctionID := 'FN' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_ID 
BEFORE INSERT ON ROLE FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.RoleID IS NULL THEN 
    v_seq := SEQ_ROLE.NEXTVAL;
    IF v_seq < 10 THEN :NEW.RoleID := 'RL0' || v_seq; ELSE :NEW.RoleID := 'RL' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_GROUP_ID 
BEFORE INSERT ON ROLE_GROUP FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.RoleGroupID IS NULL THEN 
    v_seq := SEQ_ROLE_GROUP.NEXTVAL;
    IF v_seq < 10 THEN :NEW.RoleGroupID := 'RG0' || v_seq; ELSE :NEW.RoleGroupID := 'RG' || v_seq; END IF;
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER TRG_PASSENGER_ID 
BEFORE INSERT ON PASSENGER FOR EACH ROW 
DECLARE v_seq NUMBER;
BEGIN 
  IF :NEW.PassengerID IS NULL THEN 
    v_seq := SEQ_PASSENGER.NEXTVAL;
    IF v_seq < 10 THEN :NEW.PassengerID := 'PA0' || v_seq; ELSE :NEW.PassengerID := 'PA' || v_seq; END IF;
  END IF; 
END;
/
