CREATE SEQUENCE SEQ_AIRLINE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AIRPORT START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AIRCRAFT START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROUTE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FLIGHT START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USERS START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ACCOUNT START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMER START WITH 16 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEAT START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOKING START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TICKET START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BAGGAGE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRANSACTION_HISTORY START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEATCLASSPRICE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FUNCTION START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE_GROUP START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PASSENGER START WITH 100 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE OR REPLACE TRIGGER TRG_AIRLINE_ID 
BEFORE INSERT ON AIRLINE FOR EACH ROW 
BEGIN IF :NEW.AirlineID IS NULL THEN :NEW.AirlineID := 'AL' || LPAD(SEQ_AIRLINE.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_AIRPORT_ID 
BEFORE INSERT ON AIRPORT FOR EACH ROW 
BEGIN IF :NEW.AirportID IS NULL THEN :NEW.AirportID := 'AP' || LPAD(SEQ_AIRPORT.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_AIRCRAFT_ID 
BEFORE INSERT ON AIRCRAFT FOR EACH ROW 
BEGIN IF :NEW.AircraftID IS NULL THEN :NEW.AircraftID := 'AC' || LPAD(SEQ_AIRCRAFT.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_ROUTE_ID 
BEFORE INSERT ON ROUTE FOR EACH ROW 
BEGIN IF :NEW.RouteID IS NULL THEN :NEW.RouteID := 'RT' || LPAD(SEQ_ROUTE.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_FLIGHT_ID 
BEFORE INSERT ON FLIGHT FOR EACH ROW 
BEGIN IF :NEW.FlightID IS NULL THEN :NEW.FlightID := 'FL' || LPAD(SEQ_FLIGHT.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_USERS_ID 
BEFORE INSERT ON USERS FOR EACH ROW 
BEGIN IF :NEW.UserID IS NULL THEN :NEW.UserID := 'US' || SEQ_USERS.NEXTVAL; END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_ID 
BEFORE INSERT ON ACCOUNT FOR EACH ROW 
BEGIN IF :NEW.AccountID IS NULL THEN :NEW.AccountID := 'ACC' || SEQ_ACCOUNT.NEXTVAL; END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_CUSTOMER_ID 
BEFORE INSERT ON CUSTOMER FOR EACH ROW 
BEGIN IF :NEW.CustomerID IS NULL THEN :NEW.CustomerID := 'CUS' || SEQ_CUSTOMER.NEXTVAL; END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_ID 
BEFORE INSERT ON EMPLOYEE FOR EACH ROW 
BEGIN IF :NEW.EmployeeID IS NULL THEN :NEW.EmployeeID := 'EMP' || LPAD(SEQ_EMPLOYEE.NEXTVAL,5,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_ID 
BEFORE INSERT ON SEAT FOR EACH ROW 
BEGIN IF :NEW.SeatID IS NULL THEN :NEW.SeatID := 'ST' || LPAD(SEQ_SEAT.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_BOOKING_ID 
BEFORE INSERT ON BOOKING FOR EACH ROW 
BEGIN IF :NEW.BookingID IS NULL THEN :NEW.BookingID := 'BK' || LPAD(SEQ_BOOKING.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_TICKET_ID 
BEFORE INSERT ON TICKET FOR EACH ROW 
BEGIN IF :NEW.TicketID IS NULL THEN :NEW.TicketID := 'TK' || LPAD(SEQ_TICKET.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_ID 
BEFORE INSERT ON PAYMENT FOR EACH ROW 
BEGIN IF :NEW.PaymentID IS NULL THEN :NEW.PaymentID := 'PM' || LPAD(SEQ_PAYMENT.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_BAGGAGE_ID 
BEFORE INSERT ON BAGGAGE FOR EACH ROW 
BEGIN IF :NEW.BaggageID IS NULL THEN :NEW.BaggageID := 'BG' || LPAD(SEQ_BAGGAGE.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_TRANSACTION_HISTORY_ID 
BEFORE INSERT ON TRANSACTION_HISTORY FOR EACH ROW 
BEGIN IF :NEW.TransactionID IS NULL THEN :NEW.TransactionID := 'TH' || LPAD(SEQ_TRANSACTION_HISTORY.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_SEATCLASSPRICE_ID 
BEFORE INSERT ON SEATCLASSPRICE FOR EACH ROW 
BEGIN IF :NEW.PriceID IS NULL THEN :NEW.PriceID := 'SCP' || LPAD(SEQ_SEATCLASSPRICE.NEXTVAL,5,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_FUNCTION_ID 
BEFORE INSERT ON "FUNCTION" FOR EACH ROW 
BEGIN IF :NEW.FunctionID IS NULL THEN :NEW.FunctionID := 'FN' || LPAD(SEQ_FUNCTION.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_ID 
BEFORE INSERT ON ROLE FOR EACH ROW 
BEGIN IF :NEW.RoleID IS NULL THEN :NEW.RoleID := 'RL' || LPAD(SEQ_ROLE.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_GROUP_ID 
BEFORE INSERT ON ROLE_GROUP FOR EACH ROW 
BEGIN IF :NEW.RoleGroupID IS NULL THEN :NEW.RoleGroupID := 'RG' || LPAD(SEQ_ROLE_GROUP.NEXTVAL,6,'0'); END IF; END;
/

CREATE OR REPLACE TRIGGER TRG_PASSENGER_ID 
BEFORE INSERT ON PASSENGER FOR EACH ROW 
BEGIN IF :NEW.PassengerID IS NULL THEN :NEW.PassengerID := 'PA' || LPAD(SEQ_PASSENGER.NEXTVAL,6,'0'); END IF; END;
/
