
/* =========================================================
   1. BẢNG DANH MỤC: AIRLINE, AIRPORT, ROUTE, AIRCRAFT
   ========================================================= */
-- BẢNG HÃNG HÀNG KHÔNG (AIRLINE)
INSERT ALL
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL01', 'Vietnam Airlines', 'Vietnam', '19001100', 'contact@vietnamairlines.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL02', 'VietJet Air', 'Vietnam', '19001886', 'contact@vietjetair.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL03', 'Bamboo Airways', 'Vietnam', '19001166', 'contact@bambooairways.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL04', 'Singapore Airlines', 'Singapore', '+6562238888', 'contact@singaporeairlines.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL05', 'Qatar Airways', 'Qatar', '+97440230000', 'contact@qatarairways.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL06', 'Emirates', 'UAE', '+971600555555', 'contact@emirates.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL07', 'Korean Air', 'South Korea', '+8215882001', 'contact@koreanair.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL08', 'Japan Airlines', 'Japan', '+81367333062', 'contact@japanairlines.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL09', 'Air France', 'France', '+33969393654', 'contact@airfrance.com')
    INTO AIRLINE (AirlineID, AirlineName, Country, Phone, Email) VALUES ('AL10', 'Delta', 'USA', '+18002211212', 'contact@delta.com')
SELECT 1 FROM DUAL;

-- BẢNG SÂN BAY (AIRPORT)
INSERT ALL
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP01', 'Tan Son Nhat', 'Ho Chi Minh', 'Vietnam', 'SGN')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP02', 'Noi Bai', 'Hanoi', 'Vietnam', 'HAN')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP03', 'Da Nang', 'Da Nang', 'Vietnam', 'DAD')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP04', 'Phu Quoc', 'Phu Quoc', 'Vietnam', 'PQC')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP05', 'Changi', 'Singapore', 'Singapore', 'SIN')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP06', 'Suvarnabhumi', 'Bangkok', 'Thailand', 'BKK')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP07', 'Hamad', 'Doha', 'Qatar', 'DOH')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP08', 'Dubai Intl', 'Dubai', 'UAE', 'DXB')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP09', 'Incheon', 'Seoul', 'South Korea', 'ICN')
    INTO AIRPORT (AirportID, AirportName, City, Country, IATACode) VALUES ('AP10', 'Narita', 'Tokyo', 'Japan', 'NRT')
SELECT 1 FROM DUAL;

-- BẢNG TUYẾN BAY (ROUTE)
INSERT ALL
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT01', 'AP07', 'AP10', 408, 60)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT02', 'AP06', 'AP04', 2940, 314)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT03', 'AP07', 'AP04', 2636, 283)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT04', 'AP09', 'AP10', 2153, 235)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT05', 'AP03', 'AP04', 3731, 393)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT06', 'AP09', 'AP03', 1269, 146)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT07', 'AP04', 'AP03', 3985, 418)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT08', 'AP07', 'AP03', 613, 81)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT09', 'AP09', 'AP10', 922, 112)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT10', 'AP08', 'AP01', 2637, 283)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT11', 'AP02', 'AP05', 1554, 175)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT12', 'AP02', 'AP04', 3677, 387)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT13', 'AP09', 'AP01', 2913, 311)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT14', 'AP07', 'AP04', 1814, 201)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT15', 'AP02', 'AP09', 500, 70)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT16', 'AP06', 'AP02', 1528, 172)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT17', 'AP06', 'AP02', 311, 51)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT18', 'AP02', 'AP08', 4122, 432)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT19', 'AP08', 'AP05', 2079, 227)
    INTO ROUTE (RouteID, DepartureAirportID, ArrivalAirportID, Distance, EstimatedTime) VALUES ('RT20', 'AP02', 'AP09', 1330, 153)
SELECT 1 FROM DUAL;

-- BẢNG MÁY BAY (AIRCRAFT)
INSERT ALL
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC01', 'AL09', 'Airbus A350', 250, 2018)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC02', 'AL06', 'Airbus A321', 250, 2023)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC03', 'AL05', 'Airbus A320', 150, 2024)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC04', 'AL01', 'Airbus A320', 300, 2015)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC05', 'AL09', 'Boeing 787', 300, 2020)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC06', 'AL05', 'Airbus A350', 150, 2018)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC07', 'AL04', 'Boeing 777', 300, 2020)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC08', 'AL06', 'Airbus A320', 250, 2018)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC09', 'AL10', 'Boeing 777', 250, 2022)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC10', 'AL09', 'Airbus A321', 250, 2022)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC11', 'AL07', 'Boeing 787', 250, 2021)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC12', 'AL09', 'Airbus A350', 300, 2015)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC13', 'AL06', 'Airbus A350', 150, 2020)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC14', 'AL03', 'Airbus A321', 300, 2020)
    INTO AIRCRAFT (AircraftID, AirlineID, Model, Capacity, ManufactureYear) VALUES ('AC15', 'AL09', 'Boeing 787', 250, 2017)
SELECT 1 FROM DUAL;

/* =========================================================
   [TỐI ƯU HÓA] AUTO GENERATE GHẾ NGỒI (BẢNG SEAT) BẰNG PL/SQL
   ========================================================= */
DECLARE
  v_first INT; v_bus INT; v_prem INT; v_eco INT;
  v_colIdx INT; v_row INT; v_seatCounter INT;
  v_seatName VARCHAR2(10); v_seatId VARCHAR2(20);
  TYPE string_array IS TABLE OF VARCHAR2(1);
  v_cols string_array := string_array('A','B','C','D','E','F');
BEGIN
  FOR ac IN (SELECT AircraftID, Capacity FROM AIRCRAFT) LOOP
    IF MOD(TO_NUMBER(SUBSTR(ac.AircraftID, 3)), 3) = 0 THEN
      v_first := TRUNC(ac.Capacity * 0.1);
      v_bus := TRUNC(ac.Capacity * 0.2);
      v_prem := TRUNC(ac.Capacity * 0.1);
      v_eco := ac.Capacity - v_first - v_bus - v_prem;
    ELSIF MOD(TO_NUMBER(SUBSTR(ac.AircraftID, 3)), 3) = 1 THEN
      v_first := 0; v_prem := 0;
      v_bus := TRUNC(ac.Capacity * 0.2);
      v_eco := ac.Capacity - v_bus;
    ELSE
      v_first := 0; v_bus := 0; v_prem := 0;
      v_eco := ac.Capacity;
    END IF;
    v_row := 1; v_colIdx := 1; v_seatCounter := 1;
    FOR i IN 1..v_first LOOP
      v_seatName := v_row || v_cols(v_colIdx);
      v_seatId := ac.AircraftID || '_' || v_seatCounter;
      INSERT INTO SEAT (SeatID, AircraftID, SeatNumber, Class) VALUES (v_seatId, ac.AircraftID, v_seatName, 'First Class');
      v_seatCounter := v_seatCounter + 1; v_colIdx := v_colIdx + 1;
      IF v_colIdx > 6 THEN v_colIdx := 1; v_row := v_row + 1; END IF;
    END LOOP;
    IF v_colIdx > 1 THEN v_row := v_row + 1; v_colIdx := 1; END IF;
    FOR i IN 1..v_bus LOOP
      v_seatName := v_row || v_cols(v_colIdx);
      v_seatId := ac.AircraftID || '_' || v_seatCounter;
      INSERT INTO SEAT (SeatID, AircraftID, SeatNumber, Class) VALUES (v_seatId, ac.AircraftID, v_seatName, 'Business');
      v_seatCounter := v_seatCounter + 1; v_colIdx := v_colIdx + 1;
      IF v_colIdx > 6 THEN v_colIdx := 1; v_row := v_row + 1; END IF;
    END LOOP;
    IF v_colIdx > 1 THEN v_row := v_row + 1; v_colIdx := 1; END IF;
    FOR i IN 1..v_prem LOOP
      v_seatName := v_row || v_cols(v_colIdx);
      v_seatId := ac.AircraftID || '_' || v_seatCounter;
      INSERT INTO SEAT (SeatID, AircraftID, SeatNumber, Class) VALUES (v_seatId, ac.AircraftID, v_seatName, 'Premium Economy');
      v_seatCounter := v_seatCounter + 1; v_colIdx := v_colIdx + 1;
      IF v_colIdx > 6 THEN v_colIdx := 1; v_row := v_row + 1; END IF;
    END LOOP;
    IF v_colIdx > 1 THEN v_row := v_row + 1; v_colIdx := 1; END IF;
    FOR i IN 1..v_eco LOOP
      v_seatName := v_row || v_cols(v_colIdx);
      v_seatId := ac.AircraftID || '_' || v_seatCounter;
      INSERT INTO SEAT (SeatID, AircraftID, SeatNumber, Class) VALUES (v_seatId, ac.AircraftID, v_seatName, 'Economy');
      v_seatCounter := v_seatCounter + 1; v_colIdx := v_colIdx + 1;
      IF v_colIdx > 6 THEN v_colIdx := 1; v_row := v_row + 1; END IF;
    END LOOP;
  END LOOP;
  COMMIT;
END;
/

/* =========================================================
   2. BẢNG NGƯỜI DÙNG (TÁCH BIỆT RÕ RÀNG)
   ========================================================= */
-- BẢNG NGƯỜI DÙNG CHUNG (USERS)
INSERT ALL
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US01', 'Nhan Vien 1', 'admin@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US02', 'Nhan Vien 2', 'staff2@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US03', 'Nhan Vien 3', 'staff3@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US04', 'Nhan Vien 4', 'staff4@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US05', 'Nhan Vien 5', 'staff5@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US06', 'Khach Hang 1', 'customer1@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US07', 'Khach Hang 2', 'customer2@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US08', 'Khach Hang 3', 'customer3@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US09', 'Khach Hang 4', 'customer4@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US10', 'Khach Hang 5', 'customer5@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US11', 'Khach Hang 6', 'customer6@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US12', 'Khach Hang 7', 'customer7@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US13', 'Khach Hang 8', 'customer8@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US14', 'Khach Hang 9', 'customer9@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US15', 'Khach Hang 10', 'customer10@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US16', 'Khach Hang 11', 'customer11@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US17', 'Khach Hang 12', 'customer12@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US18', 'Khach Hang 13', 'customer13@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US19', 'Khach Hang 14', 'customer14@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US20', 'Khach Hang 15', 'customer15@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US21', 'Khach Hang 16', 'customer16@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US22', 'Khach Hang 17', 'customer17@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US23', 'Khach Hang 18', 'customer18@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US24', 'Khach Hang 19', 'customer19@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US25', 'Khach Hang 20', 'customer20@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US26', 'Khach Hang 21', 'customer21@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US27', 'Khach Hang 22', 'customer22@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US28', 'Khach Hang 23', 'customer23@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US29', 'Khach Hang 24', 'customer24@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US30', 'Khach Hang 25', 'customer25@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US31', 'Khach Hang 26', 'customer26@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US32', 'Khach Hang 27', 'customer27@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US33', 'Khach Hang 28', 'customer28@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US34', 'Khach Hang 29', 'customer29@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US35', 'Khach Hang 30', 'customer30@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US36', 'Khach Hang 31', 'customer31@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US37', 'Khach Hang 32', 'customer32@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US38', 'Khach Hang 33', 'customer33@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US39', 'Khach Hang 34', 'customer34@mail.com', 0)
    INTO USERS (UserID, FullName, Email, IsDeleted) VALUES ('US40', 'Khach Hang 35', 'customer35@mail.com', 0)
SELECT 1 FROM DUAL;

-- BẢNG TÀI KHOẢN ĐĂNG NHẬP (ACCOUNT)
INSERT ALL
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC01', 'US01', 'admin', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC02', 'US02', 'staff2', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC03', 'US03', 'staff3', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC04', 'US04', 'staff4', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC05', 'US05', 'staff5', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC06', 'US06', 'customer1', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC07', 'US07', 'customer2', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC08', 'US08', 'customer3', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC09', 'US09', 'customer4', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC10', 'US10', 'customer5', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC11', 'US11', 'customer6', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC12', 'US12', 'customer7', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC13', 'US13', 'customer8', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC14', 'US14', 'customer9', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC15', 'US15', 'customer10', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC16', 'US16', 'customer11', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC17', 'US17', 'customer12', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC18', 'US18', 'customer13', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC19', 'US19', 'customer14', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC20', 'US20', 'customer15', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC21', 'US21', 'customer16', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC22', 'US22', 'customer17', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC23', 'US23', 'customer18', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC24', 'US24', 'customer19', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC25', 'US25', 'customer20', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC26', 'US26', 'customer21', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC27', 'US27', 'customer22', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC28', 'US28', 'customer23', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC29', 'US29', 'customer24', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC30', 'US30', 'customer25', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC31', 'US31', 'customer26', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC32', 'US32', 'customer27', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC33', 'US33', 'customer28', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC34', 'US34', 'customer29', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC35', 'US35', 'customer30', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC36', 'US36', 'customer31', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC37', 'US37', 'customer32', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC38', 'US38', 'customer33', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC39', 'US39', 'customer34', 'pass', 'ACTIVE', 0)
    INTO ACCOUNT (AccountID, UserID, UserName, Password, Status, IsDeleted) VALUES ('ACC40', 'US40', 'customer35', 'pass', 'ACTIVE', 0)
SELECT 1 FROM DUAL;

-- BẢNG NHÂN VIÊN (EMPLOYEE)
INSERT ALL
    INTO EMPLOYEE (EmployeeID, AccountID, FullName, Position, Email) VALUES ('EMP01', 'ACC01', 'Nhan Vien 1', 'System Admin', 'staff1@mail.com')
    INTO EMPLOYEE (EmployeeID, AccountID, FullName, Position, Email) VALUES ('EMP02', 'ACC02', 'Nhan Vien 2', 'Ticketing Staff', 'staff2@mail.com')
    INTO EMPLOYEE (EmployeeID, AccountID, FullName, Position, Email) VALUES ('EMP03', 'ACC03', 'Nhan Vien 3', 'Ticketing Staff', 'staff3@mail.com')
    INTO EMPLOYEE (EmployeeID, AccountID, FullName, Position, Email) VALUES ('EMP04', 'ACC04', 'Nhan Vien 4', 'Ticketing Staff', 'staff4@mail.com')
    INTO EMPLOYEE (EmployeeID, AccountID, FullName, Position, Email) VALUES ('EMP05', 'ACC05', 'Nhan Vien 5', 'Ticketing Staff', 'staff5@mail.com')
SELECT 1 FROM DUAL;

-- BẢNG KHÁCH HÀNG THÀNH VIÊN (CUSTOMER)
INSERT ALL
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS01', 'ACC06', 'Khach Hang 1', 'Male', 'P100006')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS02', 'ACC07', 'Khach Hang 2', 'Male', 'P100007')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS03', 'ACC08', 'Khach Hang 3', 'Male', 'P100008')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS04', 'ACC09', 'Khach Hang 4', 'Male', 'P100009')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS05', 'ACC10', 'Khach Hang 5', 'Male', 'P100010')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS06', 'ACC11', 'Khach Hang 6', 'Female', 'P100011')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS07', 'ACC12', 'Khach Hang 7', 'Male', 'P100012')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS08', 'ACC13', 'Khach Hang 8', 'Male', 'P100013')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS09', 'ACC14', 'Khach Hang 9', 'Female', 'P100014')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS10', 'ACC15', 'Khach Hang 10', 'Female', 'P100015')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS11', 'ACC16', 'Khach Hang 11', 'Female', 'P100016')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS12', 'ACC17', 'Khach Hang 12', 'Male', 'P100017')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS13', 'ACC18', 'Khach Hang 13', 'Male', 'P100018')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS14', 'ACC19', 'Khach Hang 14', 'Male', 'P100019')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS15', 'ACC20', 'Khach Hang 15', 'Female', 'P100020')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS16', 'ACC21', 'Khach Hang 16', 'Female', 'P100021')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS17', 'ACC22', 'Khach Hang 17', 'Female', 'P100022')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS18', 'ACC23', 'Khach Hang 18', 'Male', 'P100023')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS19', 'ACC24', 'Khach Hang 19', 'Female', 'P100024')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS20', 'ACC25', 'Khach Hang 20', 'Male', 'P100025')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS21', 'ACC26', 'Khach Hang 21', 'Male', 'P100026')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS22', 'ACC27', 'Khach Hang 22', 'Female', 'P100027')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS23', 'ACC28', 'Khach Hang 23', 'Male', 'P100028')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS24', 'ACC29', 'Khach Hang 24', 'Male', 'P100029')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS25', 'ACC30', 'Khach Hang 25', 'Male', 'P100030')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS26', 'ACC31', 'Khach Hang 26', 'Male', 'P100031')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS27', 'ACC32', 'Khach Hang 27', 'Female', 'P100032')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS28', 'ACC33', 'Khach Hang 28', 'Female', 'P100033')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS29', 'ACC34', 'Khach Hang 29', 'Female', 'P100034')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS30', 'ACC35', 'Khach Hang 30', 'Male', 'P100035')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS31', 'ACC36', 'Khach Hang 31', 'Female', 'P100036')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS32', 'ACC37', 'Khach Hang 32', 'Female', 'P100037')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS33', 'ACC38', 'Khach Hang 33', 'Male', 'P100038')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS34', 'ACC39', 'Khach Hang 34', 'Male', 'P100039')
    INTO CUSTOMER (CustomerID, AccountID, FullName, Gender, PassportNumber) VALUES ('CUS35', 'ACC40', 'Khach Hang 35', 'Male', 'P100040')
SELECT 1 FROM DUAL;

-- BẢNG HÀNH KHÁCH BAY (PASSENGER)
INSERT ALL
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA001', 'Hanh Khach 1', 'Female', 'PP200001')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA002', 'Hanh Khach 2', 'Female', 'PP200002')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA003', 'Hanh Khach 3', 'Female', 'PP200003')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA004', 'Hanh Khach 4', 'Female', 'PP200004')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA005', 'Hanh Khach 5', 'Male', 'PP200005')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA006', 'Hanh Khach 6', 'Male', 'PP200006')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA007', 'Hanh Khach 7', 'Female', 'PP200007')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA008', 'Hanh Khach 8', 'Female', 'PP200008')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA009', 'Hanh Khach 9', 'Male', 'PP200009')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA010', 'Hanh Khach 10', 'Male', 'PP200010')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA011', 'Hanh Khach 11', 'Female', 'PP200011')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA012', 'Hanh Khach 12', 'Male', 'PP200012')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA013', 'Hanh Khach 13', 'Female', 'PP200013')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA014', 'Hanh Khach 14', 'Female', 'PP200014')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA015', 'Hanh Khach 15', 'Female', 'PP200015')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA016', 'Hanh Khach 16', 'Male', 'PP200016')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA017', 'Hanh Khach 17', 'Female', 'PP200017')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA018', 'Hanh Khach 18', 'Male', 'PP200018')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA019', 'Hanh Khach 19', 'Male', 'PP200019')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA020', 'Hanh Khach 20', 'Male', 'PP200020')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA021', 'Hanh Khach 21', 'Female', 'PP200021')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA022', 'Hanh Khach 22', 'Female', 'PP200022')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA023', 'Hanh Khach 23', 'Female', 'PP200023')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA024', 'Hanh Khach 24', 'Female', 'PP200024')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA025', 'Hanh Khach 25', 'Male', 'PP200025')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA026', 'Hanh Khach 26', 'Female', 'PP200026')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA027', 'Hanh Khach 27', 'Female', 'PP200027')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA028', 'Hanh Khach 28', 'Female', 'PP200028')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA029', 'Hanh Khach 29', 'Male', 'PP200029')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA030', 'Hanh Khach 30', 'Female', 'PP200030')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA031', 'Hanh Khach 31', 'Female', 'PP200031')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA032', 'Hanh Khach 32', 'Male', 'PP200032')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA033', 'Hanh Khach 33', 'Male', 'PP200033')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA034', 'Hanh Khach 34', 'Male', 'PP200034')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA035', 'Hanh Khach 35', 'Male', 'PP200035')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA036', 'Hanh Khach 36', 'Female', 'PP200036')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA037', 'Hanh Khach 37', 'Female', 'PP200037')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA038', 'Hanh Khach 38', 'Male', 'PP200038')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA039', 'Hanh Khach 39', 'Male', 'PP200039')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA040', 'Hanh Khach 40', 'Male', 'PP200040')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA041', 'Hanh Khach 41', 'Female', 'PP200041')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA042', 'Hanh Khach 42', 'Female', 'PP200042')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA043', 'Hanh Khach 43', 'Female', 'PP200043')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA044', 'Hanh Khach 44', 'Male', 'PP200044')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA045', 'Hanh Khach 45', 'Male', 'PP200045')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA046', 'Hanh Khach 46', 'Female', 'PP200046')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA047', 'Hanh Khach 47', 'Female', 'PP200047')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA048', 'Hanh Khach 48', 'Female', 'PP200048')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA049', 'Hanh Khach 49', 'Female', 'PP200049')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA050', 'Hanh Khach 50', 'Male', 'PP200050')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA051', 'Hanh Khach 51', 'Female', 'PP200051')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA052', 'Hanh Khach 52', 'Male', 'PP200052')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA053', 'Hanh Khach 53', 'Male', 'PP200053')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA054', 'Hanh Khach 54', 'Male', 'PP200054')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA055', 'Hanh Khach 55', 'Male', 'PP200055')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA056', 'Hanh Khach 56', 'Female', 'PP200056')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA057', 'Hanh Khach 57', 'Female', 'PP200057')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA058', 'Hanh Khach 58', 'Male', 'PP200058')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA059', 'Hanh Khach 59', 'Male', 'PP200059')
    INTO PASSENGER (PassengerID, FullName, Gender, PassportNumber) VALUES ('PA060', 'Hanh Khach 60', 'Female', 'PP200060')
SELECT 1 FROM DUAL;

/* =========================================================
   3. CHUYẾN BAY VÀ BẢNG GIÁ
   ========================================================= */
-- BẢNG CHUYẾN BAY (FLIGHT)
INSERT ALL
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL01', 'VN101', 'AL01', 'AC03', 'RT05', SYSDATE - 2, SYSDATE - 2 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL02', 'VN102', 'AL01', 'AC04', 'RT05', SYSDATE - 1, SYSDATE - 1 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL03', 'VN103', 'AL01', 'AC13', 'RT02', SYSDATE + 1, SYSDATE + 1 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL04', 'VN104', 'AL01', 'AC08', 'RT05', SYSDATE - 4, SYSDATE - 4 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL05', 'VN105', 'AL01', 'AC13', 'RT20', SYSDATE + 6, SYSDATE + 6 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL06', 'VN106', 'AL01', 'AC15', 'RT09', SYSDATE - 3, SYSDATE - 3 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL07', 'VN107', 'AL01', 'AC12', 'RT17', SYSDATE - 1, SYSDATE - 1 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL08', 'VN108', 'AL01', 'AC01', 'RT18', SYSDATE + 4, SYSDATE + 4 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL09', 'VN109', 'AL01', 'AC11', 'RT11', SYSDATE + 5, SYSDATE + 5 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL10', 'VN110', 'AL01', 'AC07', 'RT08', SYSDATE + 3, SYSDATE + 3 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL11', 'VN111', 'AL01', 'AC07', 'RT11', SYSDATE - 5, SYSDATE - 5 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL12', 'VN112', 'AL01', 'AC14', 'RT20', SYSDATE + 7, SYSDATE + 7 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL13', 'VN113', 'AL01', 'AC01', 'RT04', SYSDATE - 5, SYSDATE - 5 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL14', 'VN114', 'AL01', 'AC01', 'RT17', SYSDATE + 1, SYSDATE + 1 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL15', 'VN115', 'AL01', 'AC07', 'RT15', SYSDATE + 5, SYSDATE + 5 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL16', 'VN116', 'AL01', 'AC13', 'RT03', SYSDATE + 5, SYSDATE + 5 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL17', 'VN117', 'AL01', 'AC05', 'RT18', SYSDATE + 9, SYSDATE + 9 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL18', 'VN118', 'AL01', 'AC01', 'RT13', SYSDATE + 6, SYSDATE + 6 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL19', 'VN119', 'AL01', 'AC05', 'RT17', SYSDATE - 2, SYSDATE - 2 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL20', 'VN120', 'AL01', 'AC12', 'RT07', SYSDATE + 7, SYSDATE + 7 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL21', 'VN121', 'AL01', 'AC14', 'RT03', SYSDATE + 4, SYSDATE + 4 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL22', 'VN122', 'AL01', 'AC12', 'RT01', SYSDATE + 2, SYSDATE + 2 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL23', 'VN123', 'AL01', 'AC08', 'RT17', SYSDATE + 5, SYSDATE + 5 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL24', 'VN124', 'AL01', 'AC07', 'RT19', SYSDATE + 0, SYSDATE + 0 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL25', 'VN125', 'AL01', 'AC03', 'RT13', SYSDATE - 1, SYSDATE - 1 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL26', 'VN126', 'AL01', 'AC09', 'RT12', SYSDATE + 3, SYSDATE + 3 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL27', 'VN127', 'AL01', 'AC11', 'RT01', SYSDATE - 1, SYSDATE - 1 + 2/24, 'COMPLETED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL28', 'VN128', 'AL01', 'AC05', 'RT19', SYSDATE + 8, SYSDATE + 8 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL29', 'VN129', 'AL01', 'AC06', 'RT03', SYSDATE + 5, SYSDATE + 5 + 2/24, 'SCHEDULED')
    INTO FLIGHT (FlightID, FlightNumber, AirlineID, AircraftID, RouteID, DepartureTime, ArrivalTime, FlightStatus) VALUES ('FL30', 'VN130', 'AL01', 'AC05', 'RT16', SYSDATE + 9, SYSDATE + 9 + 2/24, 'SCHEDULED')
SELECT 1 FROM DUAL;

-- BẢNG GIÁ (SEATCLASSPRICE)
INSERT ALL
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL01_1', 'FL01', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL01_2', 'FL01', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL01_3', 'FL01', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL01_4', 'FL01', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL02_2', 'FL02', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL02_4', 'FL02', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL03_2', 'FL03', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL03_4', 'FL03', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL04_4', 'FL04', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL05_2', 'FL05', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL05_4', 'FL05', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL06_1', 'FL06', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL06_2', 'FL06', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL06_3', 'FL06', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL06_4', 'FL06', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL07_1', 'FL07', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL07_2', 'FL07', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL07_3', 'FL07', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL07_4', 'FL07', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL08_2', 'FL08', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL08_4', 'FL08', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL09_4', 'FL09', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL10_2', 'FL10', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL10_4', 'FL10', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL11_2', 'FL11', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL11_4', 'FL11', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL12_4', 'FL12', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL13_2', 'FL13', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL13_4', 'FL13', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL14_2', 'FL14', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL14_4', 'FL14', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL15_2', 'FL15', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL15_4', 'FL15', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL16_2', 'FL16', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL16_4', 'FL16', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL17_4', 'FL17', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL18_2', 'FL18', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL18_4', 'FL18', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL19_4', 'FL19', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL20_1', 'FL20', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL20_2', 'FL20', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL20_3', 'FL20', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL20_4', 'FL20', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL21_4', 'FL21', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL22_1', 'FL22', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL22_2', 'FL22', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL22_3', 'FL22', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL22_4', 'FL22', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL23_4', 'FL23', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL24_2', 'FL24', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL24_4', 'FL24', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL25_1', 'FL25', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL25_2', 'FL25', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL25_3', 'FL25', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL25_4', 'FL25', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL26_1', 'FL26', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL26_2', 'FL26', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL26_3', 'FL26', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL26_4', 'FL26', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL27_4', 'FL27', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL28_4', 'FL28', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL29_1', 'FL29', 'First Class', 9000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL29_2', 'FL29', 'Business', 5000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL29_3', 'FL29', 'Premium Economy', 4000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL29_4', 'FL29', 'Economy', 3000000)
    INTO SEATCLASSPRICE (PriceID, FlightID, Class, Price) VALUES ('FL30_4', 'FL30', 'Economy', 3000000)
SELECT 1 FROM DUAL;

/* =========================================================
   4. GIAO DỊCH: BOOKING, TICKET, PAYMENT
   ========================================================= */
-- BẢNG HÓA ĐƠN ĐẶT CHỖ (BOOKING)
INSERT ALL
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK01', 'CUS24', 'EMP01', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK02', 'CUS14', 'EMP02', 18000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK03', 'CUS18', 'EMP04', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK04', 'CUS23', 'EMP03', 18000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK05', 'CUS11', 'EMP02', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK06', 'CUS13', 'EMP05', 27000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK07', 'CUS26', 'EMP04', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK08', 'CUS09', 'EMP01', 5000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK09', 'CUS21', 'EMP03', 5000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK10', 'CUS35', 'EMP04', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK11', 'CUS19', 'EMP02', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK12', 'CUS03', 'EMP04', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK13', 'CUS34', 'EMP05', 18000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK14', 'CUS23', 'EMP03', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK15', 'CUS16', 'EMP02', 5000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK16', 'CUS30', 'EMP05', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK17', 'CUS25', 'EMP05', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK18', 'CUS21', 'EMP01', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK19', 'CUS04', 'EMP03', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK20', 'CUS08', 'EMP05', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK21', 'CUS21', 'EMP03', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK22', 'CUS22', 'EMP02', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK23', 'CUS30', 'EMP02', 5000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK24', 'CUS13', 'EMP05', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK25', 'CUS18', 'EMP05', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK26', 'CUS01', 'EMP04', 10000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK27', 'CUS08', 'EMP02', 27000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK28', 'CUS01', 'EMP03', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK29', 'CUS21', 'EMP02', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK30', 'CUS02', 'EMP02', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK31', 'CUS18', 'EMP02', 15000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK32', 'CUS15', 'EMP02', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK33', 'CUS07', 'EMP02', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK34', 'CUS22', 'EMP05', 27000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK35', 'CUS17', 'EMP04', 18000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK36', 'CUS07', 'EMP04', 3000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK37', 'CUS06', 'EMP03', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK38', 'CUS33', 'EMP04', 6000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK39', 'CUS30', 'EMP02', 9000000, 'CONFIRMED')
    INTO BOOKING (BookingID, CustomerID, EmployeeID, TotalAmount, Status) VALUES ('BK40', 'CUS16', 'EMP04', 27000000, 'CONFIRMED')
SELECT 1 FROM DUAL;

-- BẢNG VÉ MÁY BAY (TICKET)
INSERT ALL
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK001', 'BK01', 'FL28', 'AC05_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK002', 'BK01', 'FL28', 'AC05_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK003', 'BK02', 'FL07', 'AC12_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK004', 'BK02', 'FL07', 'AC12_2', 'PA002', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK005', 'BK03', 'FL09', 'AC11_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK006', 'BK04', 'FL20', 'AC12_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK007', 'BK04', 'FL20', 'AC12_2', 'PA002', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK008', 'BK05', 'FL16', 'AC13_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK009', 'BK05', 'FL16', 'AC13_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK010', 'BK06', 'FL22', 'AC12_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK011', 'BK06', 'FL22', 'AC12_2', 'PA002', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK012', 'BK06', 'FL22', 'AC12_3', 'PA003', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK013', 'BK07', 'FL12', 'AC14_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK014', 'BK07', 'FL12', 'AC14_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK015', 'BK07', 'FL12', 'AC14_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK016', 'BK08', 'FL14', 'AC01_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK017', 'BK09', 'FL18', 'AC01_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK018', 'BK10', 'FL23', 'AC08_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK019', 'BK10', 'FL23', 'AC08_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK020', 'BK10', 'FL23', 'AC08_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK021', 'BK11', 'FL02', 'AC04_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK022', 'BK11', 'FL02', 'AC04_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK023', 'BK12', 'FL21', 'AC14_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK024', 'BK13', 'FL01', 'AC03_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK025', 'BK13', 'FL01', 'AC03_2', 'PA002', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK026', 'BK14', 'FL30', 'AC05_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK027', 'BK14', 'FL30', 'AC05_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK028', 'BK15', 'FL02', 'AC04_3', 'PA003', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK029', 'BK16', 'FL30', 'AC05_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK030', 'BK16', 'FL30', 'AC05_4', 'PA004', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK031', 'BK17', 'FL30', 'AC05_5', 'PA005', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK032', 'BK17', 'FL30', 'AC05_6', 'PA006', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK033', 'BK18', 'FL03', 'AC13_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK034', 'BK18', 'FL03', 'AC13_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK035', 'BK19', 'FL28', 'AC05_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK036', 'BK19', 'FL28', 'AC05_4', 'PA004', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK037', 'BK20', 'FL08', 'AC01_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK038', 'BK20', 'FL08', 'AC01_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK039', 'BK21', 'FL21', 'AC14_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK040', 'BK22', 'FL18', 'AC01_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK041', 'BK22', 'FL18', 'AC01_3', 'PA003', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK042', 'BK23', 'FL13', 'AC01_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK043', 'BK24', 'FL06', 'AC15_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK044', 'BK25', 'FL23', 'AC08_4', 'PA004', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK045', 'BK25', 'FL23', 'AC08_5', 'PA005', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK046', 'BK25', 'FL23', 'AC08_6', 'PA006', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK047', 'BK26', 'FL18', 'AC01_4', 'PA004', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK048', 'BK26', 'FL18', 'AC01_5', 'PA005', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK049', 'BK27', 'FL29', 'AC06_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK050', 'BK27', 'FL29', 'AC06_2', 'PA002', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK051', 'BK27', 'FL29', 'AC06_3', 'PA003', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK052', 'BK28', 'FL21', 'AC14_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK053', 'BK29', 'FL30', 'AC05_7', 'PA007', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK054', 'BK30', 'FL09', 'AC11_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK055', 'BK31', 'FL11', 'AC07_1', 'PA001', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK056', 'BK31', 'FL11', 'AC07_2', 'PA002', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK057', 'BK31', 'FL11', 'AC07_3', 'PA003', 5000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK058', 'BK32', 'FL21', 'AC14_4', 'PA004', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK059', 'BK33', 'FL21', 'AC14_5', 'PA005', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK060', 'BK33', 'FL21', 'AC14_6', 'PA006', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK061', 'BK33', 'FL21', 'AC14_7', 'PA007', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK062', 'BK34', 'FL20', 'AC12_3', 'PA003', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK063', 'BK34', 'FL20', 'AC12_4', 'PA004', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK064', 'BK34', 'FL20', 'AC12_5', 'PA005', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK065', 'BK35', 'FL22', 'AC12_4', 'PA004', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK066', 'BK35', 'FL22', 'AC12_5', 'PA005', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK067', 'BK36', 'FL23', 'AC08_7', 'PA007', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK068', 'BK37', 'FL04', 'AC08_1', 'PA001', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK069', 'BK37', 'FL04', 'AC08_2', 'PA002', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK070', 'BK37', 'FL04', 'AC08_3', 'PA003', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK071', 'BK38', 'FL28', 'AC05_5', 'PA005', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK072', 'BK38', 'FL28', 'AC05_6', 'PA006', 3000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK073', 'BK39', 'FL26', 'AC09_1', 'PA001', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK074', 'BK40', 'FL01', 'AC03_3', 'PA003', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK075', 'BK40', 'FL01', 'AC03_4', 'PA004', 9000000, 'BOOKED')
    INTO TICKET (TicketID, BookingID, FlightID, SeatID, PassengerID, Price, TicketStatus) VALUES ('TK076', 'BK40', 'FL01', 'AC03_5', 'PA005', 9000000, 'BOOKED')
SELECT 1 FROM DUAL;

-- BẢNG THANH TOÁN (PAYMENT)
INSERT ALL
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM01', 'BK01', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM02', 'BK02', 18000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM03', 'BK03', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM04', 'BK04', 18000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM05', 'BK05', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM06', 'BK06', 27000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM07', 'BK07', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM08', 'BK08', 5000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM09', 'BK09', 5000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM10', 'BK10', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM11', 'BK11', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM12', 'BK12', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM13', 'BK13', 18000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM14', 'BK14', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM15', 'BK15', 5000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM16', 'BK16', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM17', 'BK17', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM18', 'BK18', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM19', 'BK19', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM20', 'BK20', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM21', 'BK21', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM22', 'BK22', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM23', 'BK23', 5000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM24', 'BK24', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM25', 'BK25', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM26', 'BK26', 10000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM27', 'BK27', 27000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM28', 'BK28', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM29', 'BK29', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM30', 'BK30', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM31', 'BK31', 15000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM32', 'BK32', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM33', 'BK33', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM34', 'BK34', 27000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM35', 'BK35', 18000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM36', 'BK36', 3000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM37', 'BK37', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM38', 'BK38', 6000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM39', 'BK39', 9000000, 'CREDIT CARD', 'SUCCESS')
    INTO PAYMENT (PaymentID, BookingID, Amount, PaymentMethod, PaymentStatus) VALUES ('PM40', 'BK40', 27000000, 'CREDIT CARD', 'SUCCESS')
SELECT 1 FROM DUAL;

/* =========================================================
   5. PHÂN QUYỀN (Auth & Roles) - Chuẩn khớp FrameAdmin
   ========================================================= */
-- BẢNG DANH MỤC CHỨC NĂNG (FUNCTION)
INSERT ALL
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN01', 'DASHBOARD', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN02', 'FLIGHT_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN03', 'BOOKING_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN04', 'TICKET_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN05', 'CUSTOMER_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN06', 'EMPLOYEE_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN07', 'ROLE_MANAGEMENT', 0)
    INTO "FUNCTION" (FunctionID, NameFunction, IsDeleted) VALUES ('FN08', 'DATA_MANAGEMENT', 0)
SELECT 1 FROM DUAL;

-- BẢNG QUYỀN HẠN (ROLE)
INSERT ALL
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL01', 'FN01', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL02', 'FN02', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL03', 'FN03', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL04', 'FN04', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL05', 'FN05', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL06', 'FN06', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL07', 'FN07', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL08', 'FN08', 1, 1, 1, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL09', 'FN01', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL10', 'FN02', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL11', 'FN03', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL12', 'FN04', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL13', 'FN05', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL14', 'FN06', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL15', 'FN07', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL16', 'FN08', 0, 0, 0, 0, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL17', 'FN01', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL18', 'FN02', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL19', 'FN03', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL20', 'FN04', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL21', 'FN05', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL22', 'FN06', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL23', 'FN07', 1, 1, 0, 1, 1, 0)
    INTO ROLE (RoleID, FunctionID, AddPerm, EditPerm, DeletePerm, DownloadPerm, ViewPerm, IsDeleted) VALUES ('RL24', 'FN08', 1, 1, 0, 1, 1, 0)
SELECT 1 FROM DUAL;

-- BẢNG NHÓM QUYỀN (ROLE_GROUP)
INSERT ALL
    INTO ROLE_GROUP (RoleGroupID, NameRoleGroup, IsDeleted) VALUES ('RG01', 'ADMIN_GROUP', 0)
    INTO ROLE_GROUP (RoleGroupID, NameRoleGroup, IsDeleted) VALUES ('RG02', 'MANAGER_GROUP', 0)
    INTO ROLE_GROUP (RoleGroupID, NameRoleGroup, IsDeleted) VALUES ('RG03', 'STAFF_GROUP', 0)
    INTO ROLE_GROUP (RoleGroupID, NameRoleGroup, IsDeleted) VALUES ('RG04', 'CUSTOMER_GROUP', 0)
SELECT 1 FROM DUAL;

-- BẢNG GÁN NHÓM QUYỀN VỚI QUYỀN (ROLE_GROUP_ASSIGN_ROLE)
INSERT ALL
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL01', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL02', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL03', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL04', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL05', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL06', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL07', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG01', 'RL08', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL01', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL02', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL03', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL04', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL05', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG02', 'RL06', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG03', 'RL18', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG03', 'RL19', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG03', 'RL20', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG03', 'RL21', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG04', 'RL09', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG04', 'RL11', 0)
    INTO ROLE_GROUP_ASSIGN_ROLE (RoleGroupID, RoleID, IsDeleted) VALUES ('RG04', 'RL12', 0)
SELECT 1 FROM DUAL;

-- BẢNG GÁN TÀI KHOẢN VỚI NHÓM QUYỀN (ACCOUNT_ASSIGN_ROLE_GROUP)
INSERT ALL
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC01', 'RG01', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC02', 'RG02', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC03', 'RG02', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC04', 'RG03', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC05', 'RG03', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC06', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC07', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC08', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC09', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC10', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC11', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC12', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC13', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC14', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC15', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC16', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC17', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC18', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC19', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC20', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC21', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC22', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC23', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC24', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC25', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC26', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC27', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC28', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC29', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC30', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC31', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC32', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC33', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC34', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC35', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC36', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC37', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC38', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC39', 'RG04', 0)
    INTO ACCOUNT_ASSIGN_ROLE_GROUP (AccountID, RoleGroupID, IsDeleted) VALUES ('ACC40', 'RG04', 0)
SELECT 1 FROM DUAL;

commit;
